apiVersion: apps/v1
kind: Deployment
metadata:
  name: machine-dashboard-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: machine-dashboard
  template:
    metadata:
      labels:
        app: machine-dashboard
    spec:
      containers:
        - name: machine-dashboard
          image: react-vite-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: APP_TITLE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_TITLE
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
